rootProject.name = "gs-quarkus"
include("utilities")
include("qs-cache")
include("qs-config")
include("qs-getting-started")
include("qs-getting-started-with-reactive")
include("qs-security-jpa")
include("qs-security-reactive")
include("qs-security-reactive-2")
include("qs-context-propagation")
include("qs-kafka:common")
include("qs-kafka:producer")
include("qs-kafka:processor")
include("qs-redis")
include("qs-validation")
